import "bootstrap/dist/css/bootstrap.min.css"
import "bootstrap/dist/js/bootstrap.min.js"
import "@popperjs/core/dist/umd/popper.min.js"
import "./src/styles/main.scss"
import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"
