export { default as Introduction } from "./intro"
export { default as HeroSection } from "./hero"
export { default as Services } from "./services"
export { default as ClassesAd } from "./content-ad"
export { default as Portfolio } from "./portfolio"
export { default as Blog } from "./blog"
export { default as SwimingAd } from "./swiming-ad"
